/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import projeto_fl.Classes.Persistencias.Caminho_Persistencia;
import projeto_fl.Classes.Persistencias.Persistencia;
import projeto_fl.Classes.Persistencias.PersistenciaProducao;

/**
 *
 * @author soder
 */
public class InserirProducao extends javax.swing.JFrame {

     ArrayList<String> maquinas;
     ArrayList<String> producao;
      ArrayList<String> irog;
     ArrayList<JTextField> jtxtFieldmaq = new ArrayList();
     ArrayList<Object> jtxtFieldmaqProducao = new ArrayList();
     ArrayList<Object> jtxtFieldIrog = new ArrayList();
     
    public InserirProducao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        maq1 = new javax.swing.JTextField();
        maq2 = new javax.swing.JTextField();
        maq4 = new javax.swing.JTextField();
        maq3 = new javax.swing.JTextField();
        maq8 = new javax.swing.JTextField();
        maq7 = new javax.swing.JTextField();
        maq6 = new javax.swing.JTextField();
        maq5 = new javax.swing.JTextField();
        maqProducao1 = new javax.swing.JTextField();
        maqProducao2 = new javax.swing.JTextField();
        maqProducao3 = new javax.swing.JTextField();
        maqProducao4 = new javax.swing.JTextField();
        maqProducao5 = new javax.swing.JTextField();
        maqProducao6 = new javax.swing.JTextField();
        maqProducao7 = new javax.swing.JTextField();
        maqProducao8 = new javax.swing.JTextField();
        maq9 = new javax.swing.JTextField();
        maq10 = new javax.swing.JTextField();
        maq11 = new javax.swing.JTextField();
        maq12 = new javax.swing.JTextField();
        maq13 = new javax.swing.JTextField();
        maq14 = new javax.swing.JTextField();
        maq15 = new javax.swing.JTextField();
        maq16 = new javax.swing.JTextField();
        maqProducao9 = new javax.swing.JTextField();
        maqProducao10 = new javax.swing.JTextField();
        maqProducao11 = new javax.swing.JTextField();
        maqProducao12 = new javax.swing.JTextField();
        maqProducao13 = new javax.swing.JTextField();
        maqProducao14 = new javax.swing.JTextField();
        maqProducao15 = new javax.swing.JTextField();
        maqProducao16 = new javax.swing.JTextField();
        salvarProducao = new javax.swing.JButton();
        irog1 = new javax.swing.JTextField();
        irog2 = new javax.swing.JTextField();
        irog3 = new javax.swing.JTextField();
        irog4 = new javax.swing.JTextField();
        irog5 = new javax.swing.JTextField();
        irog6 = new javax.swing.JTextField();
        irog7 = new javax.swing.JTextField();
        irog8 = new javax.swing.JTextField();
        irog12 = new javax.swing.JTextField();
        irog15 = new javax.swing.JTextField();
        irog11 = new javax.swing.JTextField();
        irog9 = new javax.swing.JTextField();
        irog13 = new javax.swing.JTextField();
        irog10 = new javax.swing.JTextField();
        irog14 = new javax.swing.JTextField();
        irog16 = new javax.swing.JTextField();
        gravarDados = new javax.swing.JButton();
        fecharJanela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        maq1.setBackground(new java.awt.Color(255, 255, 204));
        maq1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq1.setText("pronto para ler");
        maq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq1ActionPerformed(evt);
            }
        });

        maq2.setBackground(new java.awt.Color(255, 255, 204));
        maq2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq2.setText("pronto para ler");
        maq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq2ActionPerformed(evt);
            }
        });

        maq4.setBackground(new java.awt.Color(255, 255, 204));
        maq4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq4.setText("pronto para ler");
        maq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq4ActionPerformed(evt);
            }
        });

        maq3.setBackground(new java.awt.Color(255, 255, 204));
        maq3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq3.setText("pronto para ler");
        maq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq3ActionPerformed(evt);
            }
        });

        maq8.setBackground(new java.awt.Color(255, 255, 204));
        maq8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq8.setText("pronto para ler");
        maq8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq8ActionPerformed(evt);
            }
        });

        maq7.setBackground(new java.awt.Color(255, 255, 204));
        maq7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq7.setText("pronto para ler");
        maq7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq7ActionPerformed(evt);
            }
        });

        maq6.setBackground(new java.awt.Color(255, 255, 204));
        maq6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq6.setText("pronto para ler");
        maq6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq6ActionPerformed(evt);
            }
        });

        maq5.setBackground(new java.awt.Color(255, 255, 204));
        maq5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq5.setText("pronto para ler");
        maq5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq5ActionPerformed(evt);
            }
        });

        maqProducao1.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao1.setText("pronto para ler");
        maqProducao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao1ActionPerformed(evt);
            }
        });

        maqProducao2.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao2.setText("pronto para ler");
        maqProducao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao2ActionPerformed(evt);
            }
        });

        maqProducao3.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao3.setText("pronto para ler");
        maqProducao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao3ActionPerformed(evt);
            }
        });

        maqProducao4.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao4.setText("pronto para ler");
        maqProducao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao4ActionPerformed(evt);
            }
        });

        maqProducao5.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao5.setText("pronto para ler");
        maqProducao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao5ActionPerformed(evt);
            }
        });

        maqProducao6.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao6.setText("pronto para ler");
        maqProducao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao6ActionPerformed(evt);
            }
        });

        maqProducao7.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao7.setText("pronto para ler");
        maqProducao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao7ActionPerformed(evt);
            }
        });

        maqProducao8.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao8.setText("pronto para ler");
        maqProducao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao8ActionPerformed(evt);
            }
        });

        maq9.setBackground(new java.awt.Color(255, 255, 204));
        maq9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq9.setText("pronto para ler");
        maq9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq9ActionPerformed(evt);
            }
        });

        maq10.setBackground(new java.awt.Color(255, 255, 204));
        maq10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq10.setText("pronto para ler");
        maq10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq10ActionPerformed(evt);
            }
        });

        maq11.setBackground(new java.awt.Color(255, 255, 204));
        maq11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq11.setText("pronto para ler");
        maq11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq11ActionPerformed(evt);
            }
        });

        maq12.setBackground(new java.awt.Color(255, 255, 204));
        maq12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq12.setText("pronto para ler");
        maq12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq12ActionPerformed(evt);
            }
        });

        maq13.setBackground(new java.awt.Color(255, 255, 204));
        maq13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq13.setText("pronto para ler");
        maq13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq13ActionPerformed(evt);
            }
        });

        maq14.setBackground(new java.awt.Color(255, 255, 204));
        maq14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq14.setText("pronto para ler");
        maq14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq14ActionPerformed(evt);
            }
        });

        maq15.setBackground(new java.awt.Color(255, 255, 204));
        maq15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq15.setText("pronto para ler");
        maq15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq15ActionPerformed(evt);
            }
        });

        maq16.setBackground(new java.awt.Color(255, 255, 204));
        maq16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maq16.setText("pronto para ler");
        maq16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maq16ActionPerformed(evt);
            }
        });

        maqProducao9.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao9.setText("pronto para ler");
        maqProducao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao9ActionPerformed(evt);
            }
        });

        maqProducao10.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao10.setText("pronto para ler");
        maqProducao10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao10ActionPerformed(evt);
            }
        });

        maqProducao11.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao11.setText("pronto para ler");
        maqProducao11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao11ActionPerformed(evt);
            }
        });

        maqProducao12.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao12.setText("pronto para ler");
        maqProducao12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao12ActionPerformed(evt);
            }
        });

        maqProducao13.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao13.setText("pronto para ler");
        maqProducao13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao13ActionPerformed(evt);
            }
        });

        maqProducao14.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao14.setText("pronto para ler");
        maqProducao14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao14ActionPerformed(evt);
            }
        });

        maqProducao15.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao15.setText("pronto para ler");
        maqProducao15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao15ActionPerformed(evt);
            }
        });

        maqProducao16.setBackground(new java.awt.Color(204, 255, 204));
        maqProducao16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maqProducao16.setText("pronto para ler");
        maqProducao16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqProducao16ActionPerformed(evt);
            }
        });

        salvarProducao.setBackground(new java.awt.Color(204, 204, 255));
        salvarProducao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        salvarProducao.setText("Carregar");
        salvarProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarProducaoActionPerformed(evt);
            }
        });

        irog1.setBackground(new java.awt.Color(153, 255, 255));
        irog1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog1.setText("pronto para ler");
        irog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog1ActionPerformed(evt);
            }
        });

        irog2.setBackground(new java.awt.Color(153, 255, 255));
        irog2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog2.setText("pronto para ler");
        irog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog2ActionPerformed(evt);
            }
        });

        irog3.setBackground(new java.awt.Color(153, 255, 255));
        irog3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog3.setText("pronto para ler");
        irog3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog3ActionPerformed(evt);
            }
        });

        irog4.setBackground(new java.awt.Color(153, 255, 255));
        irog4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog4.setText("pronto para ler");
        irog4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog4ActionPerformed(evt);
            }
        });

        irog5.setBackground(new java.awt.Color(153, 255, 255));
        irog5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog5.setText("pronto para ler");
        irog5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog5ActionPerformed(evt);
            }
        });

        irog6.setBackground(new java.awt.Color(153, 255, 255));
        irog6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog6.setText("pronto para ler");
        irog6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog6ActionPerformed(evt);
            }
        });

        irog7.setBackground(new java.awt.Color(153, 255, 255));
        irog7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog7.setText("pronto para ler");
        irog7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog7ActionPerformed(evt);
            }
        });

        irog8.setBackground(new java.awt.Color(153, 255, 255));
        irog8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog8.setText("pronto para ler");
        irog8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog8ActionPerformed(evt);
            }
        });

        irog12.setBackground(new java.awt.Color(153, 255, 255));
        irog12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog12.setText("pronto para ler");
        irog12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog12ActionPerformed(evt);
            }
        });

        irog15.setBackground(new java.awt.Color(153, 255, 255));
        irog15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog15.setText("pronto para ler");
        irog15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog15ActionPerformed(evt);
            }
        });

        irog11.setBackground(new java.awt.Color(153, 255, 255));
        irog11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog11.setText("pronto para ler");
        irog11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog11ActionPerformed(evt);
            }
        });

        irog9.setBackground(new java.awt.Color(153, 255, 255));
        irog9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog9.setText("pronto para ler");
        irog9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog9ActionPerformed(evt);
            }
        });

        irog13.setBackground(new java.awt.Color(153, 255, 255));
        irog13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog13.setText("pronto para ler");
        irog13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog13ActionPerformed(evt);
            }
        });

        irog10.setBackground(new java.awt.Color(153, 255, 255));
        irog10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog10.setText("pronto para ler");
        irog10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog10ActionPerformed(evt);
            }
        });

        irog14.setBackground(new java.awt.Color(153, 255, 255));
        irog14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog14.setText("pronto para ler");
        irog14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog14ActionPerformed(evt);
            }
        });

        irog16.setBackground(new java.awt.Color(153, 255, 255));
        irog16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        irog16.setText("pronto para ler");
        irog16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irog16ActionPerformed(evt);
            }
        });

        gravarDados.setBackground(new java.awt.Color(204, 204, 255));
        gravarDados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gravarDados.setText("Gravar e Fechar");
        gravarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarDadosActionPerformed(evt);
            }
        });

        fecharJanela.setBackground(new java.awt.Color(204, 204, 255));
        fecharJanela.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fecharJanela.setText("Fechar/Janela");
        fecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharJanelaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Maq.");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Meta");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Prod.");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Maq.");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Meta");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Prod.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(salvarProducao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maq1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(irog1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maqProducao1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maq9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maq16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(irog9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irog16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maqProducao9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maqProducao16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gravarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecharJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addComponent(jLabel2)
                .addGap(92, 92, 92)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(107, 107, 107)
                .addComponent(jLabel5)
                .addGap(92, 92, 92)
                .addComponent(jLabel6)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maqProducao1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(irog1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(maq9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(maq1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maq8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(irog9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irog16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maqProducao9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maqProducao16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gravarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecharJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq1ActionPerformed
        if(maquinas.get(0)!=null){
            maq1.setText(maquinas.get(0));
        }
    }//GEN-LAST:event_maq1ActionPerformed

    private void maq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq2ActionPerformed

    private void maq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq4ActionPerformed

    private void maq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq3ActionPerformed

    private void maq8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq8ActionPerformed

    private void maq7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq7ActionPerformed

    private void maq6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq6ActionPerformed

    private void maq5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq5ActionPerformed

    private void maqProducao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao1ActionPerformed

    private void maqProducao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao2ActionPerformed

    private void maqProducao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao3ActionPerformed

    private void maqProducao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao4ActionPerformed

    private void maqProducao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao5ActionPerformed

    private void maqProducao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao6ActionPerformed

    private void maqProducao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao7ActionPerformed

    private void maqProducao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao8ActionPerformed

    private void maq9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq9ActionPerformed

    private void maq10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq10ActionPerformed

    private void maq11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq11ActionPerformed

    private void maq12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq12ActionPerformed

    private void maq13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq13ActionPerformed

    private void maq14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq14ActionPerformed

    private void maq15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq15ActionPerformed

    private void maq16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maq16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maq16ActionPerformed

    private void maqProducao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao9ActionPerformed

    private void maqProducao10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao10ActionPerformed

    private void maqProducao11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao11ActionPerformed

    private void maqProducao12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao12ActionPerformed

    private void maqProducao13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao13ActionPerformed

    private void maqProducao14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao14ActionPerformed

    private void maqProducao15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao15ActionPerformed

    private void maqProducao16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqProducao16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maqProducao16ActionPerformed

    private void fecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharJanelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharJanelaActionPerformed

    private void salvarProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarProducaoActionPerformed
        Caminho_Persistencia cp = new Caminho_Persistencia();
        cp.persistencia("PRODUCAO.txt");
        String caminho = cp.getCaminho();
        PersistenciaProducao persistencia;
        persistencia = new PersistenciaProducao(caminho);
        System.out.println(caminho);
        HashMap prod = new HashMap();
        HashMap prod2 = new HashMap();
        prod = persistencia.leitura(0, 1);
        prod2 = persistencia.leitura(0, 2);
        maquinas = new ArrayList();
        producao = new ArrayList();
        irog = new ArrayList();
        
        jtxtFieldmaq.add(maq1);
        jtxtFieldmaq.add(maq2);
        jtxtFieldmaq.add(maq3);
        jtxtFieldmaq.add(maq4);
        jtxtFieldmaq.add(maq5);
        jtxtFieldmaq.add(maq6);
        jtxtFieldmaq.add(maq7);
        jtxtFieldmaq.add(maq8);
        jtxtFieldmaq.add(maq9);
        jtxtFieldmaq.add(maq10);
        jtxtFieldmaq.add(maq11);
        jtxtFieldmaq.add(maq12);
        jtxtFieldmaq.add(maq13);
        jtxtFieldmaq.add(maq14);
        jtxtFieldmaq.add(maq15);
        jtxtFieldmaq.add(maq16);
        
        jtxtFieldmaqProducao.add(maqProducao1);
        jtxtFieldmaqProducao.add(maqProducao2);
        jtxtFieldmaqProducao.add(maqProducao3);
        jtxtFieldmaqProducao.add(maqProducao4);
        jtxtFieldmaqProducao.add(maqProducao5);
        jtxtFieldmaqProducao.add(maqProducao6);
        jtxtFieldmaqProducao.add(maqProducao7);
        jtxtFieldmaqProducao.add(maqProducao8);
        jtxtFieldmaqProducao.add(maqProducao9);
        jtxtFieldmaqProducao.add(maqProducao10);
        jtxtFieldmaqProducao.add(maqProducao11);
        jtxtFieldmaqProducao.add(maqProducao12);
        jtxtFieldmaqProducao.add(maqProducao13);
        jtxtFieldmaqProducao.add(maqProducao14);
        jtxtFieldmaqProducao.add(maqProducao15);
        jtxtFieldmaqProducao.add(maqProducao16);
        
        jtxtFieldIrog.add(irog1);
        jtxtFieldIrog.add(irog2);
        jtxtFieldIrog.add(irog3);
        jtxtFieldIrog.add(irog4);
        jtxtFieldIrog.add(irog5);
        jtxtFieldIrog.add(irog6);
        jtxtFieldIrog.add(irog7);
        jtxtFieldIrog.add(irog8);
        jtxtFieldIrog.add(irog9);
        jtxtFieldIrog.add(irog10);
        jtxtFieldIrog.add(irog11);
        jtxtFieldIrog.add(irog12);
        jtxtFieldIrog.add(irog13);
        jtxtFieldIrog.add(irog14);
        jtxtFieldIrog.add(irog15);
        jtxtFieldIrog.add(irog16);
        
        
       for(Object chave: prod.keySet()){
           ArrayList<String> valory = new ArrayList();
           valory = (ArrayList<String>) prod.get(chave);
           maquinas.add((String) chave);
           String s = (String) valory.get(1);
           producao.add(s);
           String z = (String) valory.get(0);
           irog.add(z);
       }
       /*for(Object chave: prod2.keySet()){
           ArrayList<String> valory = new ArrayList();
           valory = (ArrayList<String>) hm.get(chave);
           irog.add((String) prod2.get(chave).toString());
           
       }*/
       int i = 0; // variável usada para percorrer os arraysLists
       for(String mq: maquinas){ //percorre as máquinas
            if(maquinas.get(i)!=null){
                jtxtFieldmaq.get(i).setText(maquinas.get(i));
                System.out.println(i+" --> "+maquinas.get(i));
                i++;
            }
       }
       int a = 0; // variável usada para percorrer os arraysLists
       for(String mq: producao){ //percorre a produção
            if(producao.get(a)!=null){
                javax.swing.JTextField maqProducao = (javax.swing.JTextField) jtxtFieldmaqProducao.get(a);
                maqProducao.setText(producao.get(a));
                System.out.println(a+" --> "+producao.get(a));
                a++;
            }
       }
       int s = 0; // variável usada para percorrer os arraysLists
       for(String ig: irog){ // para percorrer o arraylist de irog
           if(irog.get(s)!=null){
               javax.swing.JTextField irogProducao = (javax.swing.JTextField) jtxtFieldIrog.get(s);
               irogProducao.setText(irog.get(s));
               System.out.println(s+" --> "+irog.get(s));
                s++;
           }
       }
    }//GEN-LAST:event_salvarProducaoActionPerformed

    private void irog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog1ActionPerformed

    private void irog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog2ActionPerformed

    private void irog3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog3ActionPerformed

    private void irog4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog4ActionPerformed

    private void irog5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog5ActionPerformed

    private void irog6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog6ActionPerformed

    private void irog7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog7ActionPerformed

    private void irog8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog8ActionPerformed

    private void irog12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog12ActionPerformed

    private void irog15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog15ActionPerformed

    private void irog11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog11ActionPerformed

    private void irog9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog9ActionPerformed

    private void irog13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog13ActionPerformed

    private void irog10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog10ActionPerformed

    private void irog14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog14ActionPerformed

    private void irog16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irog16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irog16ActionPerformed

    private void gravarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarDadosActionPerformed
        Caminho_Persistencia cp = new Caminho_Persistencia();
        String linha = "";
        cp.persistencia("MAQUINAS/L1/maquinas.txt");
        String maquinasL1 = cp.getCaminho();
        cp.persistencia("MAQUINAS/L4/maquinas.txt");
        String maquinasL4 = cp.getCaminho();
        
        Persistencia l1 = new Persistencia(maquinasL1);
        HashMap ml1 = l1.leitura(0, 1);
        
        ////////////////////////////////////////////////////
        ArrayList<String> StringProducao = new ArrayList();
        StringProducao.add(maqProducao1.getText());
        StringProducao.add(maqProducao2.getText());
        StringProducao.add(maqProducao3.getText());
        StringProducao.add(maqProducao4.getText());
        StringProducao.add(maqProducao5.getText());
        StringProducao.add(maqProducao6.getText());
        StringProducao.add(maqProducao7.getText());
        StringProducao.add(maqProducao8.getText());
        StringProducao.add(maqProducao9.getText());
        StringProducao.add(maqProducao10.getText());
        StringProducao.add(maqProducao11.getText());
        StringProducao.add(maqProducao12.getText());
        StringProducao.add(maqProducao13.getText());
        StringProducao.add(maqProducao14.getText());
        StringProducao.add(maqProducao15.getText());
        StringProducao.add(maqProducao16.getText());
        
        ArrayList<String> StringIrog = new ArrayList();
        
        StringIrog.add(irog1.getText());
        StringIrog.add(irog2.getText());
        StringIrog.add(irog3.getText());
        StringIrog.add(irog4.getText());
        StringIrog.add(irog5.getText());
        StringIrog.add(irog6.getText());
        StringIrog.add(irog7.getText());
        StringIrog.add(irog8.getText());
        StringIrog.add(irog9.getText());
        StringIrog.add(irog10.getText());
        StringIrog.add(irog11.getText());
        StringIrog.add(irog12.getText());
        StringIrog.add(irog13.getText());
        StringIrog.add(irog14.getText());
        StringIrog.add(irog15.getText());
        StringIrog.add(irog16.getText());
        
        String mes = null;
        String dia = null;
        String ano = null;
        Calendar calendario = Calendar.getInstance();
        Locale localizacao = new Locale("pt","BR");
        mes = calendario.getDisplayName(Calendar.MONTH, Calendar.LONG, localizacao).toLowerCase();
        dia = ""+calendario.get(Calendar.DAY_OF_MONTH);
        ano = ""+calendario.get(Calendar.YEAR);
        for(int i = 1; i<10; i++){
            String in = ""+i;
            if(dia.equals(in)){
                dia = "0"+dia;
            }
        }
        /////////////////////////////////////////////////////////
       
        for(Object chave: ml1.keySet()){
            if(chave.equals(maq1.getText())){
                cp.persistencia("PRODUCAO2016/"+"L1"+"/PRODUCAO/"+mes+dia+ano+".txt");
                String caminho = cp.getCaminho();
                 System.out.println(caminho);
                PersistenciaProducao p = new PersistenciaProducao(caminho);//não fuinciona esse trecho
                for(int i = 0; i<jtxtFieldmaq.size(); i++){
                    if(StringIrog.get(i).equals("") || StringIrog.get(i)==null){
                        p.escrita(jtxtFieldmaq.get(i).getText(), StringProducao.get(i), "0"); 
                    }else{
                        p.escrita(jtxtFieldmaq.get(i).getText(), StringProducao.get(i), StringIrog.get(i)); 
                    }
                }
            }else{
                /*cp.persistencia("PRODUCAO2016/"+"L4"+"/PRODUCAO/");
                String caminho = cp.getCaminho();
                 System.out.println(caminho);
                Persistencia p = new Persistencia(caminho);
                for(Object ob: jtxtFieldmaq){
                    p.escrita("testeData", ob.toString()); 
                }*/
            }
        }
        JOptionPane.showMessageDialog(null, "arquivado!");
        this.dispose();
    }//GEN-LAST:event_gravarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirProducao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fecharJanela;
    private javax.swing.JButton gravarDados;
    private javax.swing.JTextField irog1;
    private javax.swing.JTextField irog10;
    private javax.swing.JTextField irog11;
    private javax.swing.JTextField irog12;
    private javax.swing.JTextField irog13;
    private javax.swing.JTextField irog14;
    private javax.swing.JTextField irog15;
    private javax.swing.JTextField irog16;
    private javax.swing.JTextField irog2;
    private javax.swing.JTextField irog3;
    private javax.swing.JTextField irog4;
    private javax.swing.JTextField irog5;
    private javax.swing.JTextField irog6;
    private javax.swing.JTextField irog7;
    private javax.swing.JTextField irog8;
    private javax.swing.JTextField irog9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maq1;
    private javax.swing.JTextField maq10;
    private javax.swing.JTextField maq11;
    private javax.swing.JTextField maq12;
    private javax.swing.JTextField maq13;
    private javax.swing.JTextField maq14;
    private javax.swing.JTextField maq15;
    private javax.swing.JTextField maq16;
    private javax.swing.JTextField maq2;
    private javax.swing.JTextField maq3;
    private javax.swing.JTextField maq4;
    private javax.swing.JTextField maq5;
    private javax.swing.JTextField maq6;
    private javax.swing.JTextField maq7;
    private javax.swing.JTextField maq8;
    private javax.swing.JTextField maq9;
    private javax.swing.JTextField maqProducao1;
    private javax.swing.JTextField maqProducao10;
    private javax.swing.JTextField maqProducao11;
    private javax.swing.JTextField maqProducao12;
    private javax.swing.JTextField maqProducao13;
    private javax.swing.JTextField maqProducao14;
    private javax.swing.JTextField maqProducao15;
    private javax.swing.JTextField maqProducao16;
    private javax.swing.JTextField maqProducao2;
    private javax.swing.JTextField maqProducao3;
    private javax.swing.JTextField maqProducao4;
    private javax.swing.JTextField maqProducao5;
    private javax.swing.JTextField maqProducao6;
    private javax.swing.JTextField maqProducao7;
    private javax.swing.JTextField maqProducao8;
    private javax.swing.JTextField maqProducao9;
    private javax.swing.JButton salvarProducao;
    // End of variables declaration//GEN-END:variables
}
