/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import static com.oracle.nio.BufferSecrets.instance;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import projeto_fl.Classes.Persistencias.Caminho_Persistencia;
import projeto_fl.Classes.Persistencias.Persistencia;

/**
 *
 * @author soder
 */
public class VerProducao extends javax.swing.JFrame {

    /**
     * Creates new form VerProducao
     */
    public VerProducao() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        verProducao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtxtAreaMostrarProducao = new javax.swing.JTextArea();
        voltar = new javax.swing.JButton();
        linha = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        boxMeses = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        boxDia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        boxAno = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Selecione o mês");

        verProducao.setBackground(new java.awt.Color(204, 204, 255));
        verProducao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verProducao.setText("Ver Agora");
        verProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProducaoActionPerformed(evt);
            }
        });

        JtxtAreaMostrarProducao.setBackground(new java.awt.Color(204, 255, 204));
        JtxtAreaMostrarProducao.setColumns(20);
        JtxtAreaMostrarProducao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        JtxtAreaMostrarProducao.setRows(5);
        JtxtAreaMostrarProducao.setText("coloque sempre o mês primeiro e por extenso, seguido pelo dia e ano com 2 digitos!");
        jScrollPane1.setViewportView(JtxtAreaMostrarProducao);

        voltar.setBackground(new java.awt.Color(204, 204, 255));
        voltar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        linha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        linha.setModel(new javax.swing.SpinnerNumberModel(1, null, 4, 1));
        linha.setValue(1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Selecione a Linha");

        boxMeses.setBackground(new java.awt.Color(204, 204, 255));
        boxMeses.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        boxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janeiro", "fevereiro", "marco", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubo", "novembro", "dezembro" }));
        boxMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMesesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Selecione o dia");

        boxDia.setBackground(new java.awt.Color(204, 204, 255));
        boxDia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        boxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Selecione o ano");

        boxAno.setBackground(new java.awt.Color(204, 204, 255));
        boxAno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        boxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(boxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(linha, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(verProducao)
                                .addGap(65, 65, 65)
                                .addComponent(voltar))
                            .addComponent(boxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(verProducao)
                    .addComponent(voltar)
                    .addComponent(linha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(boxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProducaoActionPerformed
        Caminho_Persistencia prod = new Caminho_Persistencia();
        String arqProd = "PRODUCAO/"+this.boxMeses.getSelectedItem().toString()+this.boxDia.getSelectedItem().toString()+this.boxAno.getSelectedItem().toString();
        System.out.println(arqProd);
        String vao = "L"+this.linha.getValue();
        prod.setCaminhoProducao(vao, arqProd);
        String DB = prod.getCaminhoProducao2016Retorno();
        Persistencia db1 = new Persistencia(DB);
        Persistencia db2 = new Persistencia(DB);
        HashMap producaoHash = db1.leitura(0, 1); // PRODUCAO
        HashMap producaoHash2 = db2.leitura(0, 2); // duas leituras diferentes
        String mega = "";
        NumberFormat instance = DecimalFormat.getInstance(new Locale("pt", "BR"));
        instance.setMaximumFractionDigits(2);
        Double dValue;
        Double dValue2;
        double x = 0;
        double y = 0;
        for(Object chave: producaoHash.keySet()){
                String sx =(String) producaoHash.get(chave);
                String sy =(String) producaoHash2.get(chave);
           sx.split(",");
           String[] syy = sy.toString().split(",");
           x = Integer.parseInt(sx);
           y = Integer.parseInt(syy[0]);
            DecimalFormat fmt = new DecimalFormat("0.00");
                double cal = (x/y)*100;
                String calculo = fmt.format(cal);
                System.out.println("produziu "+sy+" cal "+calculo);
                mega += chave+"  -->  "+" produziu: "+producaoHash.get(chave)+"\tMeta: "+producaoHash2.get(chave)+"\tIrog: "+calculo+"%\n";
    }//GEN-LAST:event_verProducaoActionPerformed
        JtxtAreaMostrarProducao.setText(arqProd+"\n"+mega);
    }
    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void boxMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMesesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProducao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JtxtAreaMostrarProducao;
    private javax.swing.JComboBox<String> boxAno;
    private javax.swing.JComboBox<String> boxDia;
    private javax.swing.JComboBox<String> boxMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner linha;
    private javax.swing.JButton verProducao;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
